apiVersion: v1
kind: Secret
metadata:
  name: fcg-gameservice-aws-secrets
  namespace: ${APP_NAME}
  labels:
    app: fcg-gameservice-aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_B64}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_B64}
  AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN_B64}