apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-gameservice-config
  namespace: ${APP_NAME}
  labels:
    app: fcg-gameservice-config
data:
  DOTNET_USE_POLLING_FILE_WATCHER: "1"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_HTTP_PORT: "8080"
  ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}