apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-fcg-gameservice-api
  namespace: ${APP_NAME}
  labels:
    app: deploy-fcg-gameservice-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-gameservice-api
  template:
    metadata:
      labels:
        app: fcg-gameservice-api
      name: fcg-gameservice-api
    spec:
      containers:
        - name: fcg-gameservice-api
          image: ${DOCKER_SERVER}/${DOCKER_REPOSITORY}:${IMAGE_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          
          #Carrega secrets e configmap
          envFrom:
            - configMapRef: 
                name: fcg-gameservice-config
            - secretRef:
                name: fcg-gameservice-mongo-secrets
            - secretRef:
                name: fcg-gameservice-elastic-secrets
            - secretRef:
                name: fcg-gameservice-aws-secrets
            - secretRef:
                name: fcg-gameservice-otel-secrets

          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: fcg-gameservice-volume
              mountPath: /logs

      volumes:
        - name: fcg-gameservice-volume
          emptyDir: {}
