apiVersion: v1
kind: Secret
metadata:
  name: fcg-gameservice-elastic-secrets
  namespace: ${APP_NAME}
  labels:
    app: fcg-gameservice-elastic-secrets
type: Opaque
data:
  ElasticSettings__ApiKey: ${ElasticSettings_ApiKey_B64}
  ElasticSettings__CloudId: ${ElasticSettings_CloudId_B64}