apiVersion: v1
kind: Secret
metadata:
  name: fcg-gameservice-elastic-secrets
  labels:
    app: fcg-gameservice-elastic-secrets
type: Opaque
data:
  ElasticSettings__ApiKey: ${ElasticSettings__ApiKey}
  ElasticSettings__CloudId: ${ElasticSettings__CloudId}