apiVersion: v1
kind: Secret
metadata:
  name: fcg-gameservice-storage-secrets
  labels:
    app: fcg-gameservice-storage-secrets
type: Opaque
data:
  AzureStorage__ConnectionString: ${AzureStorage__ConnectionString}
  AzureStorage__ProducerQueueName: ${AzureStorage__ProducerQueueName}
  AzureStorage__ConsumerQueueName: ${AzureStorage__ConsumerQueueName}