apiVersion: v1
kind: Secret
metadata:
  name: fcg-gameservice-mongo-secrets
  labels:
    app: fcg-gameservice-mongo-secrets
type: Opaque
data:
  MongoDbSettings__ConnectionString: ${MongoDbSettings__ConnectionString}
  MongoDbSettings__DatabaseName: ${MongoDbSettings__DatabaseName}