apiVersion: v1
kind: Secret
metadata:
  name: fcg-gameservice-mongo-secrets
  namespace: ${APP_NAME}
  labels:
    app: fcg-gameservice-mongo-secrets
type: Opaque
data:
  MongoDbSettings__ConnectionString: ${MongoDbSettings_ConnectionString_B64}
  MongoDbSettings__DatabaseName: ${MongoDbSettings_DatabaseName_B64}