apiVersion: v1
kind: Secret
metadata:
  name: fcg-gameservice-otel-secrets
  namespace: ${APP_NAME}
  labels:
    app: fcg-gameservice-otel-secrets
type: Opaque
data:
  OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES_B64}
  OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT_B64}
  OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS_B64}
  OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL_B64}