apiVersion: v1
kind: Service
metadata:
  name: scv-fcg-gameservice-api
  labels:
    app: scv-fcg-gameservice-api
spec:
  selector:
    app: fcg-gameservice-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080