name: Deploy to EKS

on:
  workflow_call:
    inputs:
      run-deploy:
        required: true
        type: boolean

jobs:
  deploy:
    if: ${{ inputs.run-deploy }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # necessário pois é usado AWS Academy
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Apply k8s files
        run: kubectl apply -f k8s/